on:
  create:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get version
        run: echo ::set-env name=VERSION::${GITHUB_REF#refs/*/}
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.5.0
        with:
          dotnet-version: 2.2
    
      - name: Install dependencies
        run: dotnet restore src/
    
      - name: Build
        run: dotnet build src/ --no-restore --configuration Release -p:Version=$VERSION
    
      - name: Test
        run: dotnet test src/ --no-build --no-restore
      
      - name: Pack
        run: dotnet pack src/ --no-build --no-restore --configuration Release -p:Version=$VERSION
        
      - name: Push
        env:
          NUGET_URL: "https://api.nuget.org/v3/index.json"
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        run: dotnet nuget push "src/**/*.nupkg" --source $NUGET_URL --api-key $NUGET_KEY
